initial structure
VladaGromova/FirstTask pull request #1
Opened 2021-01-21 09:32 UTC by VladaGromova

2021-01-27 15:52 UTC, FilippStankevichTR requested changes

2021-01-27 15:52 UTC, FilippStankevichTR commented on src/main/java/com/epam/task/first/ArrayCreator.java
> +                array = parser.create(line);
Array array

2021-01-27 15:52 UTC, FilippStankevichTR commented on src/main/java/com/epam/task/first/creator/ArrayParser.java
> +            number = Integer.parseInt(numbers[i]);
int number;

2021-01-27 15:52 UTC, FilippStankevichTR commented on src/main/java/com/epam/task/first/creator/ArrayParser.java
> +        String[] numbers = data.split(" ");
parts

2021-01-27 15:52 UTC, FilippStankevichTR commented on src/main/java/com/epam/task/first/creator/ArrayParser.java
> +        List listOfNumbers = new ArrayList<Integer>();
List<Integer>

2021-01-27 15:52 UTC, FilippStankevichTR commented on src/main/java/com/epam/task/first/creator/ArrayValidator.java
> +        boolean isValid = Pattern.matches("^[0-9 ]+$", line);
private static final DIGIT_PATTERN = "^[0-9 ]+$";

2021-01-27 15:52 UTC, FilippStankevichTR commented on src/main/java/com/epam/task/first/logic/ArrayLogic.java
> +                ++quantity;
quantity++;

2021-01-27 15:52 UTC, FilippStankevichTR commented on src/main/java/com/epam/task/first/logic/ArrayLogic.java
> +            newNumber = (elements.get(i))*(-1);
int newNumber

2021-01-27 15:52 UTC, FilippStankevichTR commented on src/main/java/com/epam/task/first/logic/ArraySorter.java
> +        int tmp = elements.get(firstIndex);
temp

2021-01-27 15:52 UTC, FilippStankevichTR commented on src/main/java/com/epam/task/first/entities/Array.java
> +        this.elements.addAll(Arrays.asList(elements));
this.elements  = Collections.unmodifableList(elements);

2021-01-27 15:52 UTC, FilippStankevichTR commented on src/test/java/com/epam/task/first/data/DataReaderTest.java
> +    private  final static String TEST_DATA = "C:\\Java Web Development\\projects\\FirstTask\\src\\test\\resources\\input.txt";
src/test/resources/input.txt

2021-01-27 15:52 UTC, FilippStankevichTR commented on src/test/java/com/epam/task/first/data/DataReaderTest.java
> +        List<String> expected = new ArrayList<String>();
Arrays.asList("1", "2");

2021-01-27 15:52 UTC, FilippStankevichTR commented on src/test/java/com/epam/task/first/data/DataReaderTest.java
> +        Assert.assertTrue(expected.equals(actual));
Assert.assertEquals

2021-01-27 15:52 UTC, FilippStankevichTR commented on src/test/java/com/epam/task/first/logic/ArrayCreatorTest.java
> +    static DataReader reader;
private

2021-01-28 08:23 UTC, VladaGromova reviewed
Thank you. I'll fix it.

2021-01-28 08:31 UTC, merged